accounts/urls.py
from .import views
from django.urls import path

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
]

frontend/urls.py
from django.urls import path
from .import views

app_name='frontend'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='detail'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove_single_item/<slug>/', views.remove_single_item, name='remove-single-item'),
    path('summary', views.OrderSummaryView.as_view(), name='summary'),
]

mainapp/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path,include
from mainapp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

frontend/models.py
from django.db import models
from django.shortcuts import reverse
from mainapp import settings
from django_countries.fields import CountryField
from django.contrib.auth.models import User

# Create your models here.
CATEGORY_CHOICES=(
    ('C', 'Computer'), ('M','Mobile'), ('T', 'Tablet')
)

LABEL_CHOICES=(
    ('N', 'New'), ('R','Refurbished'),('U', 'Used')
)

class Item(models.Model):
    title=models.CharField(max_length=100)
    price=models.FloatField()
    discount_price=models.FloatField(blank=True, null=True)
    category=models.CharField(choices=CATEGORY_CHOICES,max_length=5)
    label=models.CharField(choices=LABEL_CHOICES, max_length=5)
    slug=models.SlugField()
    description=models.TextField()
    image=models.ImageField()
    
    def __str__(self):
        return self.title
    
    def get_discount_percent(self):
        discount_percent= 100- (self.discount_price *100 / self.price)
        return discount_percent
    
    
    def get_item_url(self):
        return reverse('frontend:detail', kwargs={
            'slug':self.slug
        })
        
    def get_add_to_cart(self):
        return reverse('frontend:add-to-cart', kwargs={'slug':self.slug})
    
class OrderItem(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    item=models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.quantity}-{self.item.title}"
    
    def total_item_price(self):
        return self.quantity * self.item.price
        
    def total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def amount_saved(self):
        return self.total_item_price()- self.total_discount_item_price()
    
    def final_price(self):
        if self.item.discount_price:
            return self.total_discount_item_price()
        return self.total_item_price()
        
 
   
class Order(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    order_ref=models.CharField(max_length=20)
    items=models.ManyToManyField(OrderItem)
    ordered_date=models.DateField()
    ordered=models.BooleanField(default=False)
    billing_address=models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    coupon=models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    payment=models.ForeignKey('Payment',on_delete=models.SET_NULL, blank=True, null=True)
    
    delivered=models.BooleanField(default=False)
    recieved=models.BooleanField(default=False)
    refund_requested=models.BooleanField(default=False)
    refund_granted=models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.user.username
    
    def total_price(self):
        total=0
        for order_item in self.items.all():
            total+=order_item.final_price()
        return total
    
class BillingAddress(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    street_address=models.CharField(max_length=100)
    apartment=models.CharField(max_length=100)
    country=CountryField(max_length=100)
    zip=models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
    
class Coupon(models.Model):
    code=models.CharField(max_length=100)
    amount=models.FloatField()
    
    def __str__(self):
        return self.code

class Payment(models.Model):
    stripe_charge_id=models.CharField(max_length=100)
    user=models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount=models.FloatField()
    timestamp=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username
    
class Refund(models.Model):
    order=models.ForeignKey(Order, on_delete=models.CASCADE)
    reason=models.TextField()
    accepted=models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.pk}"
    
        
    
    
     
       
    
    

templates/base.html
{% load static %}
{% load cart_template_tag %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %} ECOM {% endblock title %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">ECOM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'frontend:home' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.get_username }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">Profile</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign Out</a></li>
                        </ul>
                    </li>

                    {% else %}
                    <li class="nav-item">
                    <a class= "nav-link active" aria-current="page" href="{% url 'accounts:login' %}"> Sign In </a>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-dark" href="{% url 'frontend:summary' %}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">{{ user | cart_count }}</span>
                    </a>
                </form>
            </div>
        </div>
    </nav>

    <div class="mt-5 pt-4">
        {% if messages %}
            {% for message in messages %}
                <div class= 'alert alert-{{ message.tags }} alert-dismissible fade show' role='alert'>
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <!-- Section-->
    {% block content %}{% endblock %}

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Ecommerce </p></div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}
    {{ object.title }}
{% endblock title %}

{% block content %}
    <section class="py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <!-- Product details container -->
                    <div class="product-details-container">
                        <!-- Product image -->
                        <img class="img-fluid product-image" src="{{ object.image.url }}" alt="Product Image" />
                        
                        <!-- Product details -->
                        <div class="product-details text-center">
                            <!-- Product name -->
                            <h2 class="product-title fw-bolder">{{ object.title }}</h2>
                            
                            <!-- Product price -->
                            <p class="product-price">
                                {% if object.discount_price %}
                                    <del class="text-muted">${{ object.price }}</del>
                                    <span class="text-danger">${{ object.discount_price }}</span>
                                    <span class="badge bg-danger">{{ object.get_discount_percent | floatformat:2 }} Off</span>
                                {% else %}
                                    <span class="text-dark">${{ object.price }}</span>
                                {% endif %}
                            </p>
                            
                            <!-- Product description -->
                            <p class="product-description">{{ object.description }}</p>
                            
                            <!-- Product category and label badges -->
                            <p class="product-badges">
                                <span class="badge bg-info">{{ object.get_category_display }}</span>
                                <span class="badge bg-success">{{ object.get_label_display }}</span>
                            </p>
                        </div>
                        
                        <!-- Product actions -->
                        <div class="product-actions text-center">
                            <a class="btn btn-outline-dark me-3" href="{% url 'frontend:home' %}">Continue Shopping</a>
                            <a class="btn btn-dark" href="{{ item.get_add_to_cart}}">Add to Cart <i class="bi-cart-fill ms-1"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %} Ecom | Home {% endblock title %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for item in object_list %}
            <div class="col mb-5">
                <div class="card shadow h-100">
                    <!-- Product image-->
                    <img class="card-img-top p-2" src="{{ item.image.url }}"alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ item.title }}</h5>
                            <!-- Product price-->

                            {% if item.discount_price %}
                            <p><del class="mt-2 text-danger"> ${{item.price}} </del>
                            ${{item.discount_price}} </p>
                            <span class="badge round-pill bg-danger"> %{{ item.get_discount_percent | floatformat:2 }} </span>
                
                            
                            {% else %}
                            <p>${{ item.price }} </p>
                            {% endif %}

                                <p class= "btn btn-success btn-sm">{{ item.get_category_display }} </p>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ item.get_item_url}}">View options</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>      
</section>



{% endblock%}

    
    
    
    

    

templates/login.html
{% extends "base.html" %}
{% load static %}

{% block siteTitle %}Login{% endblock %}

{% block content %}
    
    <div class= "container">
        <form method= "post" >
            {% csrf_token %}
            {{ signin_form }}
            <button class= "btn btn-info"  type="submit"> Sign in </button>

        </form>

        <p> Please <a href= "{% url 'accounts:signup' %}"> Sign Up </a> for an account </p>
    </div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block siteTitle %} Sign Up {% endblock %}

{% block content %}
    

<div class= " container "  >
    <form method= "post" >
        {% csrf_token %}
        {{ form }}
        <button type="submit "  class= " btn btn-info "> Sign Up </button>
        
    
    </form>



</div>


    
{% endblock %}

templates/summary.html
{% extends "base.html" %}

{% block title %}
    Ecom | Summary 
{% endblock title %}

{% block content %}
    <section class="py-5">
        <div class="container table-responsive">
            <h4>Order Summary</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>

                            {% if order_item.item.discount_price %}
                                <td>{{ order_item.item.discount_price }}</td>
                            {% else %}
                                <td>{{ order_item.item.price }}</td>
                            {% endif %}

                            <td class="text-right">
                                <a href=" {% url 'frontend:remove-single-item' order_item.item.slug %}"><i class="bi bi-dash-circle mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'frontend:add-to-cart' order_item.item.slug %}">
                                    <i class="bi bi-plus-circle ml-2"></i>
                                </a>
                            </td>

                            {% if order_item.item.discount_price %}
                                <td class="text-right">{{ order_item.total_discount_item_price }}
                                    <span class="badge rounded-pill bg-info ml-2">
                                        Saving: {{ order_item.amount_saved | floatformat:2 }}
                                    </span>
                                </td>
                            {% else %}
                                <td class="text-right">{{ order_item.total_item_price }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}

                    {% if object.total_price %}
                        <tr>
                            <td colspan="4"><b>Order Total</b></td>
                            <td class="text-right"><b>{{ object.total_price }}</b></td>
                        </tr>
                    {% endif %}
                    
                    <tr>
                        <td colspan="4"><button class="btn btn-warning float-right">Proceed to check out</button>
                        <a href="/" button class="btn btn-info float-right mr-2" >Continue Shopping </button></a></td>
                    </tr>


                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/test.html
THIS IS A TEST